// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WedAPI_APP.Data;

#nullable disable

namespace WedAPI_APP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241208054208_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WedAPI_APP.Data.Merchandise", b =>
                {
                    b.Property<Guid>("MerchandiseCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MerchandiseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("MerchandiseDiscuss")
                        .HasColumnType("tinyint");

                    b.Property<string>("MerchandiseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MerchandisePrice")
                        .HasColumnType("float");

                    b.HasKey("MerchandiseCode");

                    b.ToTable("Merchandises");
                });
#pragma warning restore 612, 618
        }
    }
}
